### ISSUE TITLE
Sprint Review Script

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-admin#10]
@birchamp -- please review and make any adjustments needed
- open tabs in browser to following locations:
	- This one shows the books that are currently in the tN repo: https://git.door43.org/Es-419_gl/es-419_tn/
	- This one is show how Exodus is missing from manifest: https://git.door43.org/Es-419_gl/es-419_tn/src/branch/master/manifest.yaml
	- https://git.door43.org/Es-419_gl/es-419_twl
- open gA with Netlify link (or locally as a back up plan)
- logout if logged in
- login
- set org to Es-419_gl and language to Es-419
- Click continue to go to the book package checks page
- discuss how the UI will be changing
- compare check results with the repos in other tabs
- discuss what version 1 will include:
	- The UI changes
	- The TA and TW resource checks
	- The OBS checks
	- For missing repos/manifests, allow admin to create repos and to create a starter manifest for the resource
	- Once the UI changes are made, then QA tests will be created
- Mockup:
![image](https://user-images.githubusercontent.com/1289437/142215468-864c80e5-54a6-4adb-a030-bc5256840d26.png)

- target date for version 1: End of Year?

**Comment by birchamp** [comment]
@mandolyte The OKR https://app.clickup.com/t/1jfq2xu also has the repo creation piece. So the admin has to be able to create book packages.

**Comment by mandolyte** [comment]
@birchamp  edited above to include repo creation; I also included creating a "starter" manifest. 

I was curious about the phrasing "create book packages". To my ear, that implies a lot more than book package structural setup.
