### ISSUE TITLE
SPIKE: Learn Gitea/DCS API that applies to creating releases

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-admin#113]
Include documentation and a step by step manual solution. What will the interaction with Gitea look like for this?

**Comment by birchamp** [comment]
Abel may have some insight on this.

**Comment by mandolyte** [comment]
Swagger for QA: https://qa.door43.org/api/swagger#

To see all the releases: https://qa.door43.org/api/swagger#/repository/repoListReleases:
![image](https://user-images.githubusercontent.com/1289437/157900519-f030c2e4-05e5-4430-86fb-d2c752d652ff.png)

**Comment by mandolyte** [comment]
AP to create a release is described here:
https://qa.door43.org/api/swagger#/repository/repoCreateRelease

**Comment by mandolyte** [comment]
Currently in QA DCS, there are no releases for es-419_gl/es-419_tn:
![image](https://user-images.githubusercontent.com/1289437/157909716-32d11a73-4c8d-4142-b79b-ef556c6e1d7f.png)

**Comment by richmahn** [comment]
Just remember, a release is a Gitea thing, but our DCS server code will put that release into the Catalog **IF** the manifest.yaml file is valid, as it is in your example ("Catalog (prod)" badge on your release). If it isn't, the release will still be made, and you'll still get the same response when you make it, but will not have a Catalog entry (Invalid badge by the release).

If you are making the release from the master branch, one way to verify that making a release will also result in a Catalog entry is if the master branch itself is in the catalog (all master branches have a catalog entry where stage=latest). So if https://qa.door43.org/api/catalog/v5/entry/es-419_gl/es-419_tn/master doesn't return a 500 error, you are good to go on making a release from master that will appear in the catalog. Hope that makes sense. 

Example of bad master branch (no stage=latest for this repo!): https://qa.door43.org/api/catalog/v5/entry/richmahn/en_tn/master

Example of good master branch (has a stage=latest stage): https://qa.door43.org/api/catalog/v5/entry/unfoldingWord/en_tn/master

**Comment by mandolyte** [comment]
@richmahn 
To summarize...
- I can create a release as I've already shown
- tX will add to the release all the assets
- I should only create a release if the manifest is valid, else tX will not create the assets
- I can determine whether the manifest is valid using the simple GET you show above against the master branch (500 error means invalid; else OK)


Give the above, I think it would be nice to show why the manifest is invalid. Could you expose an endpoint for this? I'll file an enhancement request to put this on the table for you.

**Comment by mandolyte** [comment]
@richmahn @birchamp 
For further clarification... 
1. *What are the assets that tX adds to the release?* And are these the ones that GLs need?
2. *Will the tX pipleline create the assets for all resource types?* Those are enumerated below and are the ones in play at this time (2022-03-14 ~ π day!!)
