### ISSUE TITLE
Mock up UI/X for the admin to create a release for a single repo

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-admin#114]

**Comment by birchamp** [comment]
@birchamp mock up some ideas for this

**Comment by mandolyte** [comment]
@birchamp Spent some time looking at how gA works now (which is based on gE, of course). Currently, the so-called "Account Settings" page is shown when the user selects it from the nav menu. (Shouldn't we rename this to simply "Settings"?)

So we could do the same thing by adding to that menu something like "Resource Releases".

The page would show:
- each resource (repo), the current latest release version (if any), the state of the manifest for each
- if the manifest is valid, it would have a button offering to release the master branch
- if clicked, a dialog would show asking for a tag to apply to the release with a continue button and a cancel button
- if the continue button is clicked, then the dialog would go away and when the release is completed, the resource info on the page would update accordingly (alternatively, the dialog could stay on screen until the release is completed and then show the status; the info on the screen would also update once the dialog is dismissed)

Other things to consider:
- Each repo would have its own card and have all the features offered by the workspace RCL
- The card could have an option query/show details about the master branch, at least, all the files that are present.
- If Repos do not exist or do not have a manifest, some of the same features in the BP page could be either moved to this page or be offered on both pages.

**Comment by mandolyte** [comment]
@birchamp Sure, I'll try to make something more visual.

The act of creating a release is the easy part as I see it. I think the bigger problem is how to sensibly design a ui/x that lets the user do it.

So far I can think of three ways:

### way 1
Retain the the "book package view" of the world that exists now by allowing multiple actions per resource (see #85 for other reasons to allow multiple actions). In other words, I could be looking at the card for the book of Titus and, for each "valid" resource that exists, a second action could be clicked to release the repo. Releasing a repo while look at a single book in that repo feels a bit odd, but we are already doing repo level actions from the book level anyway.

### way 2
Today, opening the nav drawer and clicking Settings, will open an entire new page in the workspace. In a similar manner, we could open an entire new page in the workspace that deals with repo level concerns, including the releasing of them.

### way 3
We could a [tabbed interface](https://v4.mui.com/components/tabs/) to get the aforementioned repo page instead of using the nav in the drawer.

### way 4
There is probably a Next.js way of navigating to a new page that could be researched. *Pages* and routing to them are an integral part of Next.js, but it is an area of Next.js that I am not too familiar with. This very thing is suggested as a tutorial in the Next.js Template project [here](https://github.com/unfoldingWord-box3/next-js-template/issues/12)

**Comment by mandolyte** [comment]
[Ways to Release a Resource Repo.pdf](https://github.com/unfoldingWord/gateway-admin/files/8262529/Ways.to.Release.a.Resource.Repo.pdf)
