### ISSUE TITLE
Implement solution to create a release for a repo

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-admin#115]
The solution will implement the methods and UI/X from the other issues in this epic.

Create a FAB (floating action button) to allow the user to create a release for a repo.  This button will eventually be used for other actions such as PDF creation. 

DoD:
---
User can create a release of a repo.

**Comment by mandolyte** [comment]
@birchamp one clarification... *do you want one button to replace **both** functions*, namely:
- add a book to the workspace
- release a repo (resource)

That would follow a common mobile motif. For example, the "plus" sign in this screenshot, which presents a list of things to do when clicked:
![Screenshot (Mar 28, 2022 10_52_21 AM)](https://user-images.githubusercontent.com/1289437/160426470-979d421d-281c-4767-b6b9-9b9e7fd80156.png)

**Comment by birchamp** [comment]
I'm not sure.  I was wondering about that myself.   If we're going to use the tab view like the mockups show then we could have the main function (create Book) as the upper right button, create user button on the users tab, create assignment on the task tab.

**Comment by mandolyte** [comment]
Here is a screen shot of where the repo release page is invoked from within the nav drawer:
![image](https://user-images.githubusercontent.com/1289437/161543347-d4dedf1d-9aac-482a-a11b-3f5ee7e04c4c.png)

**Comment by mandolyte** [comment]
To Do:
1. As soon as the resource is selected, then two things must be done:
  a. Verify that the master branch has a valid manifest. If it does not then the release will not show in the catalog, which is the whole point of doing a release.
  b. If there is a valid manifest, then get the latest release version to show to the user.
3. Insert between the dropdown and version text entry an information status. It will be one of the following:
  - Cannot release: manifest is not valid
  - No existing releases. This will be the first one.
  - Last release was: vXXX

**Comment by mandolyte** [comment]
How to determine if a manifest is valid for a resource repo:
TBD

**Comment by mandolyte** [comment]
**How to identify latest release...**
 _Case 1:_ There is no release yet.
The API:
```sh
curl -X 'GET' \
  'https://qa.door43.org/api/v1/repos/es-419_gl/es-419_tn/releases?draft=false&pre-release=false&page=1&limit=9999' \
  -H 'accept: application/json'
```

This returns a body of `[]`. I.e., an empty array. Thus no releases exist yet.

_Case 2:_ There are existing releases.
The API:
```sh
curl -X 'GET' \
  'https://qa.door43.org/api/v1/repos/unfoldingword/en_tn/releases?draft=false&pre-release=false&page=1&limit=9999' \
  -H 'accept: application/json'
```

Snippet of returned body:
```json
[
  {
    "id": 875880,
    "tag_name": "v58",
    "target_commitish": "master",
    "name": "Version 58",
    "body": "This is version 58 of the unfoldingWord® Translation Notes for the Bible.
  }
  ... elided
]
```

Since the results are conveniently returned in last-in-first-out order, then `results[0].tag_name` will yield the latest version, namely, `v58`

**Comment by mandolyte** [comment]
Next up... using the form inputs and the user clicks to create the release...

Sample URL for POST:
https://qa.door43.org/api/v1/repos/es-419_gl/es-419_tn/releases

Here is sample JSON for the POST.
```json
{
  "tag_name": "v1.0.0",
  "target_commitish": "master",
  "name": "v1.0.0",
  "body": "First release of es-419 Translation Notes",
  "draft": false,
  "prerelease": false
}
```

There are three expected response statuses:
- 201: success
- 404: not found
- 409: json format error

**Comment by richmahn** [comment]
@mandolyte 

I actually think it is best to go by the catalog API v5 endpoint rather than the Gitea v1 endopint which has validated the release to be catalog-worthy:

So:

1) no catalog release:
https://qa.door43.org/api/catalog/v5/search/es-419_gl/es-419_tn

2) has catalog release:
https://qa.door43.org/api/catalog/v5/search/unfoldingword/en_tn

This doesn't require draft and pre-release set to false as by default it is only production releases. I'm suggesting this because anyone can make a release with even bad data, but can't get into the catalog unless it it has been validated (of course we currently only validate the manifest.yaml file, but in the future there might be more things to check)
