### ISSUE TITLE
update manifest upon release

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-admin#117]
Make the needed changes to the manifest when the user clicks release, but prior to actually creating the release.

**Comment by mandolyte** [comment]
@richmahn what changes need to be made to the manifest prior to releasing?

**Comment by mandolyte** [comment]
@richmahn at this moment, namely 2022-11-29T08:18:00, the manifest [here](https://qa.door43.org/unfoldingWord/en_tn/src/branch/master/manifest.yaml) has the version of the resource, the source, and dates.

Not sure about that last one. Here is what it is now:
```yaml
  relation:
    - en/ult?v=41
    - en/ust?v=40
    - hbo/uhb?v=2.1.30
    - el-x-koine/ugnt?v=0.30
    - en/ta?v=33
    - en/tq?v=38
    - en/tw?v=36
```

@superdav42 did you touch these?

@richmahn is there any nice way to obtain this info other than an API call per resource type?

**Comment by mandolyte** [comment]
I don't think there is any general way for us to update the relation section automatically when releasing. So I propose that we leave it as well as the remainder of the manifest to be updated as the admins normally do.

**Comment by richmahn** [comment]
@mandolyte Sounds like the best way.

**Comment by elsylambert** [comment]
@mandolyte Please give me steps to test the manifest upon release. Thanks.

**Comment by elsylambert** [comment]
https://discord.com/channels/867746700390563850/906161562287480902/1051906998867861515

**Comment by elsylambert** [comment]
Looks good and works as expected as per the comment above ^^ in v0.9.0-rc.1 build 53752e1
