### ISSUE TITLE
Release options dialog

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-admin#119]
release notes - markdown?
release stage: prod, pre-prod (ask @richmahn about what stages are useful)

**Comment by mandolyte** [comment]
@richmahn @birchamp 
At the moment, the body of the JSON sent to create a release looks like this:
```json
      body: `{
        "tag_name": "${version}",
        "target_commitish": "master",
        "name": "${version}",
        "body": "Release ${version} of ${languageId}_${resourceId}",
        "draft": false,
        "prerelease": false
      }`
```

I have the following questions:
1. I use the user supplied value for "version" for both `tag_name` and `name`. Should these be different?
2. For `target_commitish` I use "master". However, shouldn't we first develop a recommended / standard workflow for the admins to use? And if that workflow says to create a tagged branch to release from, then I will need to ask them for the branch to use. (see note below)
3. Currently, the values for draft and prerelease are hardcoded to be false. 
  - A technical question: can both be set to true? or does this return a 409 error?
  - If both are false, then this means "prod" - correct?
  - Should the app allow either value? or just prerelease?

NOTE: 
1. If the recommended workflow is to release from a "tagged" branch (ie, its name looks like the version), then the app could easily enforce this. 
2. If release branches are used, then the admin has an opportunity to "prune" the branch to remove any files that are not ready to be released. Of course, I may be overestimating their Git skills?

**Comment by richmahn** [comment]
@mandolyte 

1. Name is the title, so a human readable name. I sometimes just put "Version 1" where for the tag I put "v1", but they can both be "v1" or whatever
2. Yes, best to make a release branch as I do for publishing Book Packages so I can freeze it, then validate, then release so I know nothing has changed. I update the manifest.yaml file in that branch, then I merge the release branch back into master so it has the updated manifest.yaml file and anything else.
3. Both false means prod, yes. And you can be drafting a pre-release, so doubt there is a problem, just like in the UI: https://git.door43.org/richmahn/en_obs/releases/tag/v1
HOWEVER, I see that pre-release takes precedence over draft when adding to the catalog...definitely should be Draft first. Oops! Honestly, we never should have been using draft...it wasn't meant to be a release stage, but just so you can draft the release notes and make a temporary tag (users can't see it, including git users). We should just ignore doing anything with drafts. So to answer your question, just use prerelease, never draft. It behaves odd as it is just a way to draft release notes.

**Comment by mandolyte** [comment]
At present the release form looks like the below, letting the user select a resource and then supplying a version to use:
![image](https://user-images.githubusercontent.com/1289437/179515036-f938a545-a379-421e-98c9-be7f09d76492.png)

Based on the above, the form needs the following:
- Radio buttons allowing the user to select either production or pre-release (default to production)
- A place to enter a title (name) for the release. The default could be simply "Version ${version}" (so if they supply v42 as the version number, then the name might default to "Version v42" or perhaps "Version 42".

@richmahn @birchamp -- Sound ok?

In the next post, I'll sketch out what happens if they proceed.

**Comment by birchamp** [comment]
@mandolyte Are we not going to include release notes?

**Comment by mandolyte** [comment]
After the admin proceeds to release a repo, the following steps are performed on the admin's behalf:
1. create a branch named same as the version (say "v42"); let's call this a *release branch*
2. note: this effectively freezes the data
3. create the release from the release branch

**Questions**
1. Should there be an option to remove files from the release branch, prior to releasing?
2. Should there be updates to the manifest prior to releasing? (if so what are they)

**Complications**
1. If files can be removed, then the release branch cannot be merged back into master.
2. If the manifest is updated, then:
   - the changes must be replicated on the master branch if files can be removed
   - the changes may be merged into master if files are not allowed to be removed.


@birchamp

**Comment by mandolyte** [comment]
> @mandolyte Are we not going to include release notes?

Updated! Thanks

**Comment by richmahn** [comment]
@mandolyte Looks good. I'd go with "Version 42" instead of "Version v42", but other than that, don't see a problem.

**Comment by mandolyte** [comment]
I guess until I understand what must be updated upon release in the manifest, not sure how the impact would be to update master first then create the branch.

I was thinking of this as a long single transaction (in database terminology). If at any point, it fails, how to you abort the transaction and rollback any updates that should be there.

**Comment by birchamp** [comment]
@mandolyte @richmahn  My thought is that the release branch is simply a subset of the master so we only have to release the books that are ready.  If changes need to be made to what was release then a new release needs to be made.   I see no interruption between the app creating the release branch and then releasing.  It's just a mechanical necessity, not a stopping point for the user to adjust anything.

**Comment by richmahn** [comment]
@mandolyte Off the top of my head, if we do go the route that an aligned Bible book signifies a BP being done/published, then it would be any books not aligned or not fully aligned that get removed from any book related repo.

**Comment by mandolyte** [comment]
@elsylambert Some testing notes:
# Repo Release Testing
Repo: https://qa.door43.org/fa_gl/fa_tq
(org=fa_gl and lang=fa)

*Current state*: no releases have been done

Start gatewayAdmin and use app drawer to go to the Account Settings page.

Select org `fa_gl` and language `fa - Persian (Farsi)`

Click "Save and Continue" button.

Use app drawer to go to the "Release Repository" page.

Select "Translation Questions" as the resource to release.

Select "Pre-Release" as the Release Type.

Enter "v1" (as recommended on page) for the version.

Enter "Version 1" for the Release Name.

Copy and pasted the below into the Release Notes.
```
*This is version 35 of the unfoldingWord® Translation Questions (TSV) for the Bible. Download the Resource Container source files and PDFs below or get PDFs from [https://www.unfoldingword.org/utq/](https://www.unfoldingword.org/utq/).*

**Note** that you can see this resource on [Door43](https://door43.org/u/unfoldingWord/en_tq/v35/) or in [translationStudio](https://www.unfoldingword.org/translationstudio).

**Change** for this release is the following Book Packages complete: 1 Peter (1PE)

**Note** that TQ is now TSV files (although they will also be backported to markdown TQ in Door43-Catalog)

## [](https://qa.door43.org/unfoldingWord/en_tq/releases#book-package-consistency-check)Book Package Consistency Check

The following books have undergone a Book Package consistency check:

-   Exodus (EXO)
-   Ruth (RUT)
-   Ezra (EZR)
-   Nehemiah (NEH)
-   Esther (EST)
-   Obadiah (OBA)
-   Jonah (JON)
-   Luke (LUK)
-   John (JHN)
-   Ephesians (EPH)
-   Philippians (PHP)
-   Colossians (COL)
-   1 Thessalonians (1TH)
-   1 Timothy (1TI)
-   2 Timothy (2TI)
-   Titus (TIT)
-   Philemon (PHM)
-   James (JAS)
-   1 Peter (1PE)
-   2 Peter (2PE)
-   1 John (1JN)
-   2 John (2JN)
-   3 John (3JN)
-   Jude (JUD)
```

After a few seconds, if all is well, this status message will be shown on the page just above the footer:
```
Status: Created release v1 of fa_tq
```
Finally, click the Close button to return to the home page (book package page).

Verify using this [link(https://qa.door43.org/fa_gl/fa_tq/releases)] to go to the release page for this repo. It will now have a "Version 1" release. Also look for the following:
- Your identity as the one who made the release
- The complete release notes
- Tag of "v1"
- Catalog lable reading "Catalog (prod)".

**Comment by richmahn** [comment]
@elsylambert added

**Comment by elsylambert** [comment]
Verified in v0.24.0 build 275a8f2 QA. Both Release option: Production and Pre-Release work as expected. The Release page looks good and the Release can be deleted using the edit link.

**Comment by mandolyte** [comment]
Change in direction... now enabling multiple book package release process.
