### ISSUE TITLE
Creating the manifest should check for language and checking level 2

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-admin#125]
The language attribute in the manifest   is important for tC updates dialog. Also the checking level must be set to level 2

DOD:
When a manifest is created for a new repo, the language attribute is set and checking level is at level 2.

**Comment by elsylambert** [comment]
v0.9.0-rc.1 build 53752e1.
Looks good in the newly created Repo.
<img width="1454" alt="Screenshot 2022-12-12 at 12 54 53 PM" src="https://user-images.githubusercontent.com/51806180/207118634-a438d5ae-7144-4951-bba1-87d8078c09ae.png">
