### ISSUE TITLE
Markdown files and validation

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-admin#131]
See discord thread: https://discord.com/channels/867746700390563850/1011970774795554916/1011975354996494426

Perhaps white space at end of file is being removed before handing off to content validation?

**Comment by mandolyte** [comment]
This would be easy to fix. After removing whitespace, put a new line at the end of file

**Comment by elsylambert** [comment]
@mandolyte how can I test this issue? Please guide.

**Comment by elsylambert** [comment]
@mandolyte I ran validation for tN, tW for unfoldingword org and en, the downloaded CV files are empty.
<img width="1454" alt="Screenshot 2022-12-12 at 12 29 18 PM" src="https://user-images.githubusercontent.com/51806180/207113589-4eb5f2ea-4c05-4d37-8d41-cd16f3891941.png">

**Comment by elsylambert** [comment]
Verified for es-419_gl org for es-419, the CN files do not show the errors 950 or 538.
