### ISSUE TITLE
Convert TSV9 TNs to TSV7

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-admin#134]
As soon as uW updates to TSV7 users need to be able to convert their TSV9 to TSV7.  One of the functions gA needs to detect that the TNs are in TSV9 and offer the user the ability to convert ALL of their TN files to TSV7.

DoD:
---
Users can convert TSV9 TNs to TSV7

Details:
----
 schedule it in December (16th??)
- Work with teams to be ready to convert 
  - How hard is it for Rich to convert for them when he does the English?
  - What teams need to convert?
    - [ ] HI
    - [ ] ES-419
    - [ ] RU
    - [ ] ?? PMN?
    - [ ] ??
- Get them ready to shut down editing (announce December 1)
- Let them know how they can do it in gatewayAdmin

**Comment by mandolyte** [comment]
@birchamp should this be in v0.9? (ref: #135 )

**Comment by birchamp** [comment]
yes it should be.

**Comment by mandolyte** [comment]
NOTE: the two issues related to 9-to-7 conversion are duplicates. But at present they both contain useful information. So keeping both for now.
