### ISSUE TITLE
Repos with TN -9 column need conversion to TN-7 column

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/gateway-admin#138]
Need the ability to:
- identify repos with TN9 column format
- Once identified, The 'Action' tab should allow admins to convert their TN -9 column file to TN- 7 column

**Comment by BincyJ** [comment]
@birchamp , @mandolyte please refine further if needed

**Comment by mandolyte** [comment]
@BincyJ @birchamp @superdav42 How does this sound?

- Implement this as a repo-wide feature (thus it would be located on the drawer menu)
- It would find all TSV9 files identified by the manifest (thus enforcing that the manifest must be correct)
- It would retrieve each file, convert it to TSV7 and then post it back to the repo with the new naming conventions
- Retain the original files, providing a fall back plan
- Update the manifest with new filenames

**Comment by PhotoNomad0** [comment]
Notes:

- Roberts python script to convert: https://github.com/unfoldingWord-dev/tools/blob/develop/tsv/TN_TSV9_to_TSV7.py

**Comment by PhotoNomad0** [comment]
@mandolyte Have a PR with a prototype method for conversion: https://github.com/unfoldingWord/tsv-groupdata-parser/pull/61 .  Added note about how to use.

**Comment by elsylambert** [comment]
Looks good in v0.9.0-rc.1 build 53752e1 QA. Conversion from TSV9 to TSV 7 works fine using GA.
