### ISSUE TITLE
Idea: Do not update manifest in the master branch when doing a release

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-admin#139]
Rationale:
- the master branch is work in progress, so it should only be updated when the admin explicitly does so (currently manually and with a YAML manifest editor in the future)
- there is no purpose served by updating the manifest in the master branch

@birchamp @richmahn @superdav42

**Comment by superdav42** [comment]
Originally I was getting the current version from the manifest so it seemed like a requirement to update it in master. As it is now I'm getting the current version from the latest release tag in DCS so the manifest will not need updated for the version number.

The version number is not the only thing updated in the manifest during a release. It also adds any selected books to the projects if they don't already exist. Also it updates the modified and issued date. 

It seems a good idea to keep the manifest up-to-date with the release as much as possible. If the master branch needs to remain protected we could use the API to create a PR that the admin could manually merge after the release to ensure everything stays consistent.

Also for these resources:
```   
  'ta',
  'tw',
  'obs',
  'obs-tn',
  'obs-tq',
  'obs-twl',
  'obs-sn',
  'obs-sq',
```
A release branch is not used and the master branch is always updated directly. I guess we could change this but it didn't make sense to use a release branch when there was no project files to worry about. 

Who is the user that will be using this tool to publish? Won't they be an admin that is whitelisted to push to the master branch anyway?

**Comment by mandolyte** [comment]
This issue is closed since there is a need to update the manifest
