### ISSUE TITLE
Add new resources

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-admin#14]
Add a new resource to an existing book package

**Comment by mandolyte** [comment]
@birchamp how is this intended to be different from what repo initialization does or what tc-create does?

**Comment by birchamp** [comment]
So an example user flow I envision:
Brand new GL
1. User creates Titus
2. Ask what resources to create for Titus:  user chooses TN, TW
3. App creates TN repo, TWL repo, TW repo with Titus in the manifest
4. User adds new 3 John
5. Ask what resource to create for 3 John: user chooses TN,TQ
6. App adds 3 John to TN manifest
7. App creates the TQ repo with 3 John in the manifest
8. User clicks Titus
9. user sees that TQ doesn't exist
10. Adds TQ to Titus
11. App adds Titus to TQ manifest

**Comment by mandolyte** [comment]
All that can be done by what I'm working on now... We should go over the
scope of repo initialization

**Comment by birchamp** [comment]
The high level objective for repo initialization is that a user can begin working in tC Create.  I'm not sure that tC Create cares if a book is in the manifest or not, but I figured this is a good time to make the manifest more complete.
