### ISSUE TITLE
409 error on Releasing en_tn

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-admin#141]
v0.27.0 build 8b2843f.
Release Repository with uW org and en_tn for Genesis threw errors on the console and got endless spinner on the page.
<img width="579" alt="Screen Shot 2022-10-06 at 9 29 33 AM" src="https://user-images.githubusercontent.com/51806180/194337652-9518c088-ba62-4303-988c-659d84648f02.png">
<img width="1322" alt="Screen Shot 2022-10-06 at 9 24 21 AM" src="https://user-images.githubusercontent.com/51806180/194337675-2e335b8f-f431-401e-b05c-cb34d08dd961.png">

**Comment by elsylambert** [comment]
![image](https://user-images.githubusercontent.com/51806180/194337797-f38e49c6-60d3-495a-8ca8-0d88822f079c.png)

**Comment by elsylambert** [comment]
Still seeing this in v0.28.0 build 050cb94 QA. @superdav42 

<img width="1471" alt="Screenshot 2022-11-14 at 8 57 45 PM" src="https://user-images.githubusercontent.com/51806180/201807768-e14d0469-ed92-485c-a1b6-1b780927d5c5.png">

**Comment by superdav42** [comment]
I just tested and I did not get a 409 error. I think it was because Rich did a different release without gateway admin for TSV7. This error occurs when a release with the same name already exists. In the last test it looks like it tried to create v67 but that tag or release already existed. I'm not sure what it takes to make it happen.

**Comment by elsylambert** [comment]
<img width="1462" alt="Screenshot 2022-11-17 at 3 17 32 PM" src="https://user-images.githubusercontent.com/51806180/202550883-50991cc7-7f49-46de-9610-806fdfab00a0.png">
Worked for me in the latest https://deploy-preview-149--gateway-admin.netlify.app/.

**Comment by mandolyte** [comment]
NOTE: moved to Done
