### ISSUE TITLE
Test if Hindi problems can be fixed in gA 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-admin#146]
Hindi org: translationCore-Create-BCS  - Problems with GLT, GST, TWL, TW in gEdit

**Comment by mandolyte** [comment]
Doesn't look good. Perhaps they are using non-standard naming? 
![image](https://user-images.githubusercontent.com/1289437/198399575-4c97add1-8249-4674-9bd0-a72a13fcfb48.png)

**Comment by mandolyte** [comment]
@birchamp if their repos don't follow the conventions, then perhaps they can just rename them. It isn't hard. Just not sure of the impact of users and any of their own tooling.
