### ISSUE TITLE
Bug: tsv9 to 7 conversion

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-admin#155]
Need to copy the GLQuote value into OrigQuote if OrigQuote is empty.

**Comment by elsylambert** [comment]
Tested in v0.9.1 build dffbda3. After conversion to TSV7, 2KI has Values from GL Quote i.e English words in the Quote column.
<img width="1464" alt="Screenshot 2022-12-16 at 1 33 21 PM" src="https://user-images.githubusercontent.com/51806180/208165588-09acf1e9-b884-47b3-b0bb-98b3f7ece85a.png">
