### ISSUE TITLE
Unable to release resources for non-ASCII languages

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord/gateway-admin#176]
If a resource is non-ASCII, and has strings in the manifest.yaml file such and the language name in that language's script, gatewayAdmin fails to read the YAML file and also to re-encode it back to base64. It needs to decode the base64 content in utf8 and then encode a utf8 string back to base64.

**Comment by elsylambert** [comment]
Verified on v0.9.5 build b1e54a3 QA. Not seeing the error on release fa_tn in fa_gl org.
<img width="1394" alt="Screenshot 2023-06-08 at 11 44 28 AM" src="https://github.com/unfoldingWord/gateway-admin/assets/51806180/73c01ee0-876a-4a3f-8027-33f5e033544d">
<img width="1381" alt="Screenshot 2023-06-08 at 11 46 00 AM" src="https://github.com/unfoldingWord/gateway-admin/assets/51806180/3045105d-adc0-4a0e-a836-a7c04202f80e">
