### ISSUE TITLE
Make Pharsie Language (code `prs`) a gateway language

### ISSUE THREAD

**Issue by theNerd247** [unfoldingWord/gateway-admin#181]
The following issue was presented on Zulip: 

> We do not have all the languages embedded in gatewayAdmin. Say for e.g. Dari language which is one of the Parsi Arabic languages has the code prs and prs-AF which does not show in the gatewayAdmin language dropdown list. How do we address this issues. We are hitting a wall with this and very soon many more will follow. We need to address this sooner than later. Please help as the Parsi team needs to publish their work and this has become a major blocker.

It was discovered by @mandolyte that the `prs` language code in [languages.json](src/common/languages.json) has `"gw": false` value which is hiding it from display in gateway edit.

There are 2 shallow issues here:

1. change `prs` to be a gateway language (set `"gw": true`).
2. add the `prs-AF` as a new entry. (Though I'm not sure what the fields should be)

There is a __deeper issue__: `gateway-admin` is still pulling language codes from a static file. I'm not sure if this is on purpose. Which brings up a few questions. 

- Do we consider [uw-languages-rcl](https://github.com/unfoldingWord/uw-languages-rcl/) a source of truth (including [API for fetching `languages.json`](https://td2.unfoldingword.org/exports/langnames.json))? 
- Is this a static resource to support offline editing?
- should we remove filtering gateway languages and expose all languages on gateway-admin? (see #184 )

**Comment by theNerd247** [comment]
See #189  for the quick fix release
@elsylambert is this issue still open or should we close it since other related issues are still open?

**Comment by elsylambert** [comment]
@theNerd247 Closing this issue. We have #185 written up after a final fix is done to the language list display in gatewayAdmin by
