### ISSUE TITLE
Remove "Link to TA should also be in Note" error in TN validation

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-admin#191]
It used to be required that a Translation Note should have the link in both the note column and a link in the reference column but that is no longer the case.  

The error 787 "Link to TA should also be in Note" should be removed from the validator.

**Comment by mandolyte** [comment]
Change needs to be made in this area:
https://github.com/unfoldingWord/gateway-admin/blob/develop/src/utils/contentValidation.js#L83

@birchamp NOTE! this change will not impact any other app using content validation. The logic to filter results wasn't done in the CV RCL originally, so each app using CV has its own filter. At present, I think only tc-create would need to be changed to match this.

Of course, with more effort, this could be moved to CV itself. However, that would be extra work. Updating the filter is fairly trivial (see line reference above)

Hope to make this change later this week.

**Comment by elsylambert** [comment]
The latest develop https://develop--gateway-admin.netlify.app/ looks good with changes to tN content validation where we are no longer seeing error 787 "Link to TA should also be in Note".
