### ISSUE TITLE
Optionally Auto regenerate the manifest on UNABLE_TO_DECODE_MANIFEST

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-admin#41]
When the repo returns:
UNABLE_TO_DECODE_MANIFEST = "Unable to decode manifest"

> This will happen when the manifest is not syntactically correct YAML (or not even a YAML file at all). Proposed action is to request that file be correct manually or deleted.

The user should be able to choose to regenerate the manifest. This would take into account the pre-existing files in the repo and add them to the book list.  The user would have to be sufficiently warned that the current manifest will be overwritten.

**Comment by mandolyte** [comment]
Note: this is test 9 in `TESTING.md`
