### ISSUE TITLE
Add Content Validation scripture resources

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-admin#52]
The following are possible:
- At the finest granular level, when a resource file exists, it is possible to check it via the CV package.
- Since a book card knows all its associated resources (one level only), it is possible to check an entire book package.
- Since the workspace has access to all the books being worked on, it is possible to check all the book packages for the Gateway Language that are currently active.

**Comment by mandolyte** [comment]
### Questions on how to activate the CV process

1. Do we allow just one resource file to be checked at a time; for example, when the file is exists, the status will be OK; then we could have an action to check it.
2. Do we add a card menu or button that lets the admin check the entire book package?
3. Do we add a drawer option that lets all the book packages to be checked?
4. Do we automatically, in the background check all files?

**Comment by mandolyte** [comment]
### Questions on UI/X
1. Should results be downloaded as a spreadsheet like tc-create does?
2. Should results be shown in a (new) card? By file? or by BP?
3. Should results be shown in a popup dialog? By file? or by BP?

**Comment by birchamp** [comment]
> ### Questions on how to activate the CV process
> 
>     1. Do we allow just one resource file to be checked at a time; for example, when the file is exists, the status will be OK; then we could have an action to check it.
> 
>     2. Do we add a card menu or button that lets the admin check the entire book package?
> 
>     3. Do we add a drawer option that lets all the book packages to be checked?
> 
>     4. Do we automatically, in the background check all files?
@mandolyte 
1. For this first step we should do what's easiest while planning for both single resource checks and a whole book package.  
2. One way is to click a validation icon near the book name and be able to check off which resources to check.
3. I don't see that as a need now, but maybe users will ask for it in the future. We're trying to get to the point of publishing a BP, so we have to keep that in mind as our priority. 
4. I would love to see auto background checking but I'm concerned how much time/processing that would take, and it's not MVP.

**Comment by birchamp** [comment]
> ### Questions on UI/X
> 
>     1. Should results be downloaded as a spreadsheet like tc-create does?
> 
>     2. Should results be shown in a (new) card? By file? or by BP?
> 
>     3. Should results be shown in a popup dialog? By file? or by BP?

1. The option of downloading a spreadsheet makes sense.
2. I think a new tab is the place to start.
3. It would be helpful to have an icon beside each resource indicating the status of the last run CV for each resource. ie Empty circle for not run, yellow for lower priority issues, red for breaking issues.

**Comment by mandolyte** [comment]
@birchamp Some thoughts...
- on 1. downloading is a feature of the table component I think (I have discovered that the box3 content validation app no longer works, so I could not verify immediately).
- on 2. creating a new tab is potentially a lot of work, since we haven't done it before, to my knowledge. But I can consult with @mannycolon about it. Since I planned to save the CV results per session, why not a popup, since it would be fast. 
-  on 3. Currently there are 4 columns in the resources display. One of which is "Status". Could this column be used to show status of last CV run? If so, then at present, the values there are text. Should the CV status be shown in text as well?
